// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocnitminqrwujppazjni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jbml0bWlucXJ3dWpwcGF6am5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODQxNDIsImV4cCI6MjA3MzE2MDE0Mn0.zHuZ8rmOfGhlYluHI9je120xmU60eIqs7Xgep1s5XhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});